gooddata/gooddata-java

src/main/java/com/gooddata/UriPrefixer.java
src/test/java/com/gooddata/util/ZipUtilsTest.java

fix windows related path and uri bugs

---

src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/dataload/processes/DataloadProcess.java
src/main/java/com/gooddata/dataload/processes/ProcessService.java
src/main/java/com/gooddata/gdc/DataStoreService.java
src/test/java/com/gooddata/dataload/processes/DataloadProcessTest.java
src/test/java/com/gooddata/dataload/processes/ProcessServiceTest.java
src/test/resources/dataload/processes/process-input-withPath.json

deploy large processes through webdav

---

src/main/java/com/gooddata/dataload/processes/ProcessService.java
src/main/java/com/gooddata/dataload/processes/ProcessType.java
src/test/java/com/gooddata/dataload/processes/ProcessServiceIT.java
src/test/resources/dataload/processes/processWithoutData.json

One example can be the DATALOAD process.

Add support for creating processes without data

---

src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java
src/test/java/com/gooddata/connector/Zendesk4ProcessExecutionTest.java
src/test/resources/connector/process-execution-incremental.json

add: zd4 connector incremental load suport

---

src/main/java/com/gooddata/project/Project.java
src/main/java/com/gooddata/project/ProjectEnvironment.java
src/test/java/com/gooddata/ShowcaseAT.java
src/test/java/com/gooddata/project/ProjectTest.java
src/test/resources/project/project.json

add Project environment support

---

src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/GoodDataSettings.java
src/test/java/com/gooddata/AbstractGoodDataIT.java
src/test/java/com/gooddata/GoodDataSettingsTest.java

rewritten as agreed, closes #127

introduce connection params

---

src/main/java/com/gooddata/connector/ConnectorService.java
src/test/java/com/gooddata/connector/ConnectorServiceIT.java

introduce get for connector settings

---

src/main/java/com/gooddata/md/AbstractObj.java
src/main/java/com/gooddata/md/Attribute.java
src/main/java/com/gooddata/md/AttributeDisplayForm.java
src/main/java/com/gooddata/md/Fact.java
src/main/java/com/gooddata/md/Meta.java
src/main/java/com/gooddata/md/MetadataService.java
src/main/java/com/gooddata/md/Metric.java
src/main/java/com/gooddata/md/ObjUpdateException.java
src/main/java/com/gooddata/md/ScheduledMail.java
src/main/java/com/gooddata/md/Updatable.java
src/main/java/com/gooddata/md/report/Report.java
src/main/java/com/gooddata/md/report/ReportDefinition.java
src/test/java/com/gooddata/ShowcaseAT.java
src/test/java/com/gooddata/md/MetadataServiceIT.java
src/test/java/com/gooddata/md/MetadataServiceTest.java

introduce metadata object update

---

src/main/java/com/gooddata/md/Attribute.java
src/main/java/com/gooddata/md/Dimension.java
src/main/java/com/gooddata/md/NestedAttribute.java
src/test/java/com/gooddata/md/AttributeTest.java
src/test/java/com/gooddata/md/DimensionTest.java
src/test/java/com/gooddata/md/NestedAttributeTest.java
src/test/resources/md/attribute.json
src/test/resources/md/dimension-input.json
src/test/resources/md/dimension.json
src/test/resources/md/dimensionAttribute.json

introduce dimension metadata

---

src/main/java/com/gooddata/md/AttributeDisplayForm.java
src/main/java/com/gooddata/md/DisplayForm.java
src/test/java/com/gooddata/md/AttributeDisplayFormTest.java
src/test/java/com/gooddata/md/DisplayFormTest.java
src/test/resources/md/attributeDisplayForm-input.json
src/test/resources/md/attributeDisplayForm.json
src/test/resources/md/displayForm-input.json
src/test/resources/md/displayForm.json

add "type" and fix "default" field at display form

---

src/main/java/com/gooddata/gdc/FeatureFlag.java
src/main/java/com/gooddata/gdc/FeatureFlags.java
src/main/java/com/gooddata/project/ProjectService.java
src/test/java/com/gooddata/ShowcaseAT.java
src/test/java/com/gooddata/gdc/FeatureFlagsTest.java
src/test/java/com/gooddata/project/ProjectServiceIT.java
src/test/java/com/gooddata/project/ProjectServiceTest.java
src/test/resources/gdc/featureFlags.json

add listing of aggregated feature flags for project

---

README.md
pom.xml
src/main/java/com/gooddata/GoodData.java

See commit messages for more info.

Improve README, pom and javadocs

---

src/main/java/com/gooddata/collections/PageRequest.java
src/test/java/com/gooddata/collections/PageRequestTest.java

Offset parameter for paging may be of type int or
String.

Extend PageRequest with String offset.

---

src/main/java/com/gooddata/project/Environment.java
src/main/java/com/gooddata/project/Project.java
src/main/java/com/gooddata/project/ProjectEnvironment.java
src/main/java/com/gooddata/warehouse/Warehouse.java
src/test/java/com/gooddata/ShowcaseAT.java
src/test/java/com/gooddata/warehouse/WarehouseTest.java
src/test/resources/warehouse/warehouse-create.json
src/test/resources/warehouse/warehouse.json

add warehouse environment

---

src/test/java/com/gooddata/AbstractGoodDataAT.java
src/test/java/com/gooddata/project/ProjectServiceAT.java

fix: make acceptance tests working using static fields in tests ancestor

---

src/main/java/com/gooddata/warehouse/WarehouseService.java
src/test/java/com/gooddata/warehouse/WarehouseServiceIT.java

fix: warehouse users paging

---

src/main/java/com/gooddata/md/AttributeDisplayForm.java
src/main/java/com/gooddata/md/AttributeElement.java
src/main/java/com/gooddata/md/AttributeElements.java
src/main/java/com/gooddata/md/DisplayForm.java
src/main/java/com/gooddata/md/MetadataService.java
src/test/java/com/gooddata/md/AttributeDisplayFormTest.java
src/test/java/com/gooddata/md/AttributeElementTest.java
src/test/java/com/gooddata/md/AttributeElementsTest.java
src/test/java/com/gooddata/md/DisplayFormTest.java
src/test/java/com/gooddata/md/MetadataServiceAT.java
src/test/java/com/gooddata/md/MetadataServiceIT.java
src/test/java/com/gooddata/md/MetadataServiceTest.java
src/test/resources/md/attributeDisplayForm-input.json
src/test/resources/md/attributeElement.json
src/test/resources/md/attributeElements.json
src/test/resources/md/displayForm-input.json

introduce attribute elements support

---

src/main/java/com/gooddata/md/Dataset.java
src/test/java/com/gooddata/md/DatasetTest.java
src/test/resources/md/dataset-input.json
src/test/resources/md/dataset.json

introduce metadata dataset

---

src/main/java/com/gooddata/md/Attribute.java
src/main/java/com/gooddata/md/AttributeDisplayForm.java
src/main/java/com/gooddata/md/Dimension.java
src/main/java/com/gooddata/md/Fact.java
src/main/java/com/gooddata/md/Metric.java
src/main/java/com/gooddata/md/NestedAttribute.java
src/main/java/com/gooddata/md/ScheduledMail.java
src/main/java/com/gooddata/md/report/GridReportDefinitionContent.java
src/main/java/com/gooddata/md/report/OneNumberReportDefinitionContent.java
src/main/java/com/gooddata/md/report/Report.java
src/main/java/com/gooddata/md/report/ReportDefinition.java
src/main/java/com/gooddata/md/report/ReportDefinitionContent.java
src/main/java/com/gooddata/util/BooleanIntegerDeserializer.java
src/main/java/com/gooddata/util/BooleanStringDeserializer.java
src/test/java/com/gooddata/md/AttributeDisplayFormTest.java
src/test/java/com/gooddata/md/AttributeTest.java
src/test/java/com/gooddata/util/BooleanIntegerDeserializerTest.java
src/test/java/com/gooddata/util/BooleanStringDeserializerTest.java
src/test/resources/md/attribute-inputOrig.json
src/test/resources/md/attribute.json
src/test/resources/md/attributeDisplayForm-input.json
src/test/resources/md/attributeDisplayForm-inputOrig.json

fix updatable md objects

---

src/main/java/com/gooddata/md/Meta.java

md objects summary and title are cut off to max length

---

src/main/java/com/gooddata/md/AbstractObj.java
src/main/java/com/gooddata/md/MaqlAst.java
src/main/java/com/gooddata/md/Meta.java
src/main/java/com/gooddata/md/Metric.java
src/main/java/com/gooddata/md/ScheduledMail.java
src/main/java/com/gooddata/project/Project.java
src/test/java/com/gooddata/md/MetaTest.java
src/test/java/com/gooddata/md/MetricTest.java
src/test/java/com/gooddata/md/ObjTest.java
src/test/java/com/gooddata/project/ProjectTest.java
src/test/resources/md/attribute-input.json
src/test/resources/md/attribute-inputOrig.json
src/test/resources/md/attributeDisplayForm-input.json
src/test/resources/md/attributeDisplayForm-inputOrig.json
src/test/resources/md/dataset-input.json
src/test/resources/md/dimension-input.json
src/test/resources/md/displayForm-input.json
src/test/resources/md/fact-input.json
src/test/resources/md/meta.json
src/test/resources/md/metric-new.json
src/test/resources/md/metric-out.json
src/test/resources/md/report/oneNumberReportDefinition-input.json
src/test/resources/md/report/report-input.json

Add MaqlAst

---

.travis.yml

See http://docs.travis-ci.com/user/migrating-from-legacy/
for more info

Migrate Travis builds to container-based ones

---

README.md
pom.xml

Group id and version in readme will be changed once released
Close #242

change group id add link to upgrading

---

src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/gdc/DataStoreService.java

small step towards #99  
@martiner ready from my point of view - please review (and merge)

Use GoodData HTTP client in DataStoreService

---

src/main/java/com/gooddata/md/Fact.java
src/test/java/com/gooddata/md/FactTest.java
src/test/resources/md/fact-input.json
src/test/resources/md/fact.json

add folder to facts

---

src/main/java/com/gooddata/warehouse/Warehouse.java

removed villainously by @ostumpf in #246

bring back jdbc connection template

---

src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/notification/NotificationService.java
src/main/java/com/gooddata/notification/ProjectEvent.java
src/test/java/com/gooddata/notification/NotificationServiceAT.java
src/test/java/com/gooddata/notification/NotificationServiceIT.java
src/test/java/com/gooddata/notification/NotificationServiceTest.java
src/test/java/com/gooddata/notification/ProjectEventTest.java
src/test/resources/notification/projectEvent.json

introduce project events trigger

---

src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java
src/test/java/com/gooddata/connector/Zendesk4ProcessExecutionTest.java
src/test/resources/connector/process-execution-startDate.json

introduce zendesk connector start dates

---

src/main/java/com/gooddata/gdc/DataStoreService.java
src/test/java/com/gooddata/gdc/DatastoreServiceAT.java

Report the unauthenticated webdav 500 response conveniently

---

CONTRIBUTING.md
src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/featureflag/FeatureFlag.java
src/main/java/com/gooddata/featureflag/FeatureFlagService.java
src/main/java/com/gooddata/featureflag/FeatureFlags.java
src/main/java/com/gooddata/featureflag/ProjectFeatureFlag.java
src/main/java/com/gooddata/featureflag/ProjectFeatureFlags.java
src/main/java/com/gooddata/project/ProjectFeatureFlags.java
src/main/java/com/gooddata/project/ProjectService.java
src/test/java/com/gooddata/featureflag/FeatureFlagServiceAT.java
src/test/java/com/gooddata/featureflag/FeatureFlagServiceIT.java
src/test/java/com/gooddata/featureflag/FeatureFlagServiceTest.java
src/test/java/com/gooddata/featureflag/FeatureFlagsTest.java
src/test/java/com/gooddata/featureflag/ProjectFeatureFlagTest.java
src/test/java/com/gooddata/featureflag/ProjectFeatureFlagsTest.java
src/test/java/com/gooddata/gdc/FeatureFlagsTest.java
src/test/java/com/gooddata/project/ProjectServiceAT.java
src/test/java/com/gooddata/project/ProjectServiceIT.java
src/test/java/com/gooddata/project/ProjectServiceTest.java
src/test/resources/featureflag/featureFlags.json
src/test/resources/featureflag/projectFeatureFlag.json
src/test/resources/featureflag/projectFeatureFlags.json

Lets move support of feature flags of all scopes to it's own service. Also fix naming conventions and use DTO objects with value added as return types.

Redesign feature flag management

---

src/main/java/com/gooddata/md/DataLoadingColumn.java
src/test/java/com/gooddata/md/DataLoadingColumnTest.java
src/test/resources/md/dataLoadingColumn.json

introduce support for dataLoadingColumn

---

src/main/java/com/gooddata/md/AttributeSort.java
src/main/java/com/gooddata/md/NestedAttribute.java
src/test/java/com/gooddata/md/AttributeSortTest.java
src/test/java/com/gooddata/md/AttributeTest.java
src/test/resources/md/attribute-sortDf.json
src/test/resources/md/attributeSort.json

(de)serialize attribute.sort properly

---

src/main/java/com/gooddata/md/ProjectDashboard.java
src/test/java/com/gooddata/md/ProjectDashboardTest.java
src/test/resources/md/projectDashboard.json

Introduce ProjectDashboard md object containing dashboard tab basic info

---

pom.xml

Hopefully it would bring more readable error messages

chg: update coveralls version

---

src/main/java/com/gooddata/md/Column.java
src/main/java/com/gooddata/md/Table.java
src/main/java/com/gooddata/md/TableDataLoad.java
src/test/java/com/gooddata/md/ColumnTest.java
src/test/java/com/gooddata/md/TableDataLoadTest.java
src/test/java/com/gooddata/md/TableTest.java
src/test/resources/md/column.json
src/test/resources/md/table.json
src/test/resources/md/tableDataLoad.json

introduce physical data model md objects

---

src/main/java/com/gooddata/md/Fact.java
src/main/java/com/gooddata/md/Metric.java
src/main/java/com/gooddata/md/NestedAttribute.java
src/test/java/com/gooddata/md/MetricTest.java
src/test/resources/md/metric-folder.json

deserialize metric with folder

---

src/main/java/com/gooddata/md/MetadataService.java
src/main/java/com/gooddata/md/Obj.java
src/test/java/com/gooddata/md/MetadataServiceIT.java
src/test/java/com/gooddata/md/MetadataServiceTest.java

This saves one REST API call and closes: #112

Use createAndGet when creating metadata object

---

src/main/java/com/gooddata/md/DataLoadingColumn.java
src/test/resources/md/dataLoadingColumn.json

fix: deserialize ColumnSynchronize.precision correctly from "columnPrecision"

---

src/main/java/com/gooddata/md/AbstractObj.java
src/main/java/com/gooddata/md/Entry.java
src/main/java/com/gooddata/md/Meta.java
src/main/java/com/gooddata/md/ScheduledMail.java
src/main/java/com/gooddata/project/Project.java
src/main/java/com/gooddata/util/TagsDeserializer.java
src/main/java/com/gooddata/util/TagsSerializer.java
src/test/java/com/gooddata/md/EntryTest.java
src/test/java/com/gooddata/md/MetaTest.java
src/test/java/com/gooddata/md/ObjTest.java
src/test/java/com/gooddata/util/TagsDeserializerTest.java
src/test/java/com/gooddata/util/TagsSerializerTest.java
src/test/java/com/gooddata/util/TagsTestClass.java

Use set of strings for tags instead of one string

---

pom.xml
src/main/java/com/gooddata/account/Account.java
src/main/java/com/gooddata/account/AccountNotFoundException.java
src/main/java/com/gooddata/account/AccountService.java
src/test/java/com/gooddata/AbstractGoodDataAT.java
src/test/java/com/gooddata/account/AccountServiceAT.java
src/test/java/com/gooddata/account/AccountServiceIT.java
src/test/java/com/gooddata/account/AccountTest.java
src/test/resources/account/create-account-response.json
src/test/resources/account/create-account.json

This change has unpleasant impact on acceptance tests. Account creation requires owner of the domain to run the tests!!!

add support for creating and removing user accounts

---

src/main/java/com/gooddata/dataset/DatasetNotFoundException.java
src/main/java/com/gooddata/dataset/DatasetService.java
src/main/java/com/gooddata/dataset/DatasetUploadsInfo.java
src/main/java/com/gooddata/dataset/ProjectUploadsInfo.java
src/main/java/com/gooddata/dataset/Upload.java
src/main/java/com/gooddata/dataset/UploadStatistics.java
src/main/java/com/gooddata/dataset/Uploads.java
src/test/java/com/gooddata/dataset/DatasetServiceAT.java
src/test/java/com/gooddata/dataset/DatasetServiceIT.java
src/test/java/com/gooddata/dataset/DatasetServiceTest.java
src/test/java/com/gooddata/dataset/ProjectUploadsInfoTest.java
src/test/java/com/gooddata/dataset/UploadStatisticsTest.java
src/test/java/com/gooddata/dataset/UploadTest.java
src/test/java/com/gooddata/dataset/UploadsTest.java
src/test/resources/dataset/uploads/data-sets.json
src/test/resources/dataset/uploads/data-uploads-info.json
src/test/resources/dataset/uploads/upload.json
src/test/resources/dataset/uploads/uploads.json

Introduce project uploads information and statistics in DatasetService

---

.travis.yml
pom.xml
src/test/java/com/gooddata/md/MetadataServiceTest.java

switch build to java 8

---

src/main/java/com/gooddata/md/report/AttributeInGrid.java
src/test/java/com/gooddata/md/report/AttributeInGridTest.java

AttributeInGrid further enhancements

---

src/main/java/com/gooddata/md/MetadataService.java

SafeVarargs implies final methods, however that would prevent mocking of such methods

add SuppressWarnings unchecked instead of SafeVarargs to usedBy methods

---

src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java
src/test/java/com/gooddata/connector/Zendesk4ProcessExecutionTest.java
src/test/resources/connector/process-execution-download.json

introduce zendesk process download parameters

---

src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java

Change Zendesk4ProcessExecution.DownloadParams visibility to public

---

pom.xml

Raise Jackson version to 2.8.4 with bugfixes

---

src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/dataload/OutputStage.java
src/main/java/com/gooddata/dataload/OutputStageService.java
src/main/java/com/gooddata/util/Validate.java
src/test/java/com/gooddata/dataload/OutputStageServiceAT.java
src/test/java/com/gooddata/dataload/OutputStageServiceIT.java
src/test/java/com/gooddata/dataload/OutputStageServiceTest.java
src/test/java/com/gooddata/dataload/OutputStageTest.java
src/test/resources/dataload/outputStage.json
src/test/resources/dataload/outputStageAllFields.json
src/test/resources/dataload/outputStageNoProcess.json

this will enable to use SDK to manipulate output stage for project (related to [ADD](https://help.gooddata.com/display/doc/Automated+Data+Distribution))
resolves #398

introduce output stage

---

pom.xml
src/main/java/com/gooddata/GoodData.java
src/test/java/com/gooddata/spring/GoodDataBeansAsServicesTest.java
src/test/resources/spring/gd-annotationConfig.xml

introduce services as beans

---

src/main/java/com/gooddata/dataload/OutputStageService.java
src/test/java/com/gooddata/dataload/OutputStageServiceIT.java
src/test/java/com/gooddata/dataload/OutputStageServiceTest.java

use response body of PUT request instead of another GET request

fix occasional fails of update output stage test

---

src/main/java/com/gooddata/dataload/processes/ProcessService.java
src/main/java/com/gooddata/util/ZipHelper.java

https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful

remove file input/output stream usage, close streams in try block

---

src/main/java/com/gooddata/GoodDataRestException.java
src/main/java/com/gooddata/util/ResponseErrorHandler.java
src/test/java/com/gooddata/GoodDataRestExceptionTest.java
src/test/java/com/gooddata/util/ResponseErrorHandlerTest.java
src/test/resources/gdc/invalidError.json

fix: handle invalid error response

---

src/main/java/com/gooddata/UriPrefixer.java
src/test/java/com/gooddata/UriPrefixerTest.java

fix: double uri encoding

---

src/main/java/com/gooddata/UriPrefixer.java
src/main/java/com/gooddata/UriPrefixingClientHttpRequestFactory.java
src/test/java/com/gooddata/UriPrefixerTest.java

fix: don't let uriprefixer to strip trailing slash

---

src/main/java/com/gooddata/warehouse/Warehouse.java
src/test/java/com/gooddata/warehouse/WarehouseTest.java
src/test/resources/warehouse/warehouse-withLicense.json

resolves [#441](https://github.com/gooddata/gooddata-java/issues/441)

Include ADS license to the Warehouse object

---

.appveyor.yml

add windows CI build

---

src/main/java/com/gooddata/GoodDataRestException.java

For sake of backward binary compatibility we need this constructor removed in version 2.4.1 with commit dcdc0ee
Close #462

fix: bring back constructor

---

src/main/java/com/gooddata/connector/ConnectorService.java
src/test/java/com/gooddata/connector/ConnectorServiceIT.java

Fix Coupa instance creation

---

src/test/java/com/gooddata/featureflag/FeatureFlagServiceAT.java

https://github.com/gooddata/gooddata-java/issues/468
From R138 webapp lets user set only feature flags (settings) from catalog in c4 with appropriate access rights.

BUGFIX: Use featureFlags from the catalog

---

src/main/java/com/gooddata/warehouse/WarehouseUser.java
src/main/java/com/gooddata/warehouse/WarehouseUserRole.java
src/test/java/com/gooddata/warehouse/WarehouseUserTest.java

I've also introduced com.gooddata.warehouse.WarehouseUserRole which should be used together with these factory methods for better user experience.

Introduce factory methods to WarehouseUser

---

src/main/java/com/gooddata/account/Account.java
src/main/java/com/gooddata/account/AccountService.java
src/test/java/com/gooddata/account/AccountServiceAT.java
src/test/java/com/gooddata/account/AccountServiceIT.java
src/test/java/com/gooddata/account/AccountTest.java
src/test/resources/account/account-input.json
src/test/resources/account/account.json
src/test/resources/account/update-account.json

Add feature to update user

---

src/main/java/com/gooddata/project/CreatedInvitations.java
src/main/java/com/gooddata/project/Invitation.java
src/main/java/com/gooddata/project/Invitations.java
src/main/java/com/gooddata/project/ProjectService.java
src/test/java/com/gooddata/project/CreatedInvitationsTest.java
src/test/java/com/gooddata/project/InvitationsTest.java
src/test/java/com/gooddata/project/ProjectServiceAT.java
src/test/java/com/gooddata/project/ProjectServiceIT.java
src/test/resources/project/created-invitations-uris-only.json
src/test/resources/project/created-invitations.json
src/test/resources/project/invitations.json

add: users invitation to a project

---

src/main/java/com/gooddata/project/ProjectService.java
src/main/java/com/gooddata/project/ProjectUsersUpdateException.java
src/main/java/com/gooddata/project/ProjectUsersUpdateResult.java
src/main/java/com/gooddata/project/User.java
src/main/java/com/gooddata/project/UserInProjectNotFoundException.java
src/main/java/com/gooddata/project/Users.java
src/main/java/com/gooddata/project/UsersSerializer.java
src/test/java/com/gooddata/project/ProjectServiceAT.java
src/test/java/com/gooddata/project/ProjectServiceIT.java
src/test/java/com/gooddata/project/ProjectServiceTest.java
src/test/java/com/gooddata/project/ProjectUsersUpdateResultTest.java
src/test/java/com/gooddata/project/UsersTest.java
src/test/resources/project/addUserRequest.json
src/test/resources/project/addUsersToProject.json
src/test/resources/project/disableUserInProject.json
src/test/resources/project/projectUsersUpdateResult.json
src/test/resources/project/projectUsersUpdateResultFail.json

Introduce Add user to project and update user in project

---

src/main/java/com/gooddata/warehouse/WarehouseS3Credentials.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsException.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsNotFoundException.java
src/main/java/com/gooddata/warehouse/WarehouseService.java
src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsTest.java
src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java
src/test/java/com/gooddata/warehouse/WarehouseServiceIT.java

update and delete warehouse S3 credentials

---

src/main/java/com/gooddata/collections/MultiPageList.java
src/main/java/com/gooddata/collections/PageableList.java
src/main/java/com/gooddata/collections/PageableListSerializer.java
src/test/java/com/gooddata/collections/MultiPageListTest.java
src/test/java/com/gooddata/collections/PageableListTest.java

add getCurrentPageItems() method to PageableList

---

src/main/java/com/gooddata/collections/MultiPageList.java
src/main/java/com/gooddata/warehouse/WarehouseS3Credentials.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsException.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsList.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsListDeserializer.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsListSerializer.java
src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsNotFoundException.java
src/test/java/com/gooddata/collections/MultiPageListTest.java
src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsExceptionTest.java
src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsListTest.java
src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsTest.java
src/test/java/com/gooddata/warehouse/WarehouseServiceTest.java

use standard copyright text

---

src/main/java/com/gooddata/md/MetadataService.java
src/main/java/com/gooddata/md/Obj.java
src/test/java/com/gooddata/md/MetadataServiceAT.java
src/test/java/com/gooddata/md/MetadataServiceTest.java

allow to specify identifier when creating object

---

pom.xml
src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/auditevent/AuditEvent.java
src/main/java/com/gooddata/auditevent/AuditEventPageRequest.java
src/main/java/com/gooddata/auditevent/AuditEventService.java
src/main/java/com/gooddata/auditevent/AuditEvents.java
src/main/java/com/gooddata/auditevent/AuditEventsDeserializer.java
src/main/java/com/gooddata/auditevent/AuditEventsForbiddenException.java
src/main/java/com/gooddata/auditevent/AuditEventsSerializer.java
src/test/java/com/gooddata/account/AccountServiceIT.java
src/test/java/com/gooddata/auditevent/AuditEventPageRequestTest.java
src/test/java/com/gooddata/auditevent/AuditEventServiceAT.java
src/test/java/com/gooddata/auditevent/AuditEventServiceIT.java
src/test/java/com/gooddata/auditevent/AuditEventServiceTest.java
src/test/java/com/gooddata/auditevent/AuditEventTest.java
src/test/java/com/gooddata/auditevent/AuditEventsTest.java
src/test/resources/auditevents/auditEvent.json
src/test/resources/auditevents/auditEventWithParam.json
src/test/resources/auditevents/auditEventWithParamAndLink.json
src/test/resources/auditevents/auditEvents.json
src/test/resources/auditevents/auditEventsPage2.json
src/test/resources/auditevents/emptyAuditEvents.json
src/test/resources/auditevents/userAuditEvents.json

add audit events

---

src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java

Reenable acceptance tests for S3 credentials

---

src/main/java/com/gooddata/notification/Channel.java
src/main/java/com/gooddata/notification/Configuration.java
src/main/java/com/gooddata/notification/EmailConfiguration.java
src/main/java/com/gooddata/notification/MessageTemplate.java
src/main/java/com/gooddata/notification/NotificationService.java
src/main/java/com/gooddata/notification/Subscription.java
src/main/java/com/gooddata/notification/TimerEvent.java
src/main/java/com/gooddata/notification/Trigger.java
src/main/java/com/gooddata/notification/TriggerCondition.java
src/test/java/com/gooddata/notification/ChannelTest.java
src/test/java/com/gooddata/notification/ConditionTest.java
src/test/java/com/gooddata/notification/EmailConfigurationTest.java
src/test/java/com/gooddata/notification/MessageTemplateTest.java
src/test/java/com/gooddata/notification/NotificationServiceAT.java
src/test/java/com/gooddata/notification/NotificationServiceIT.java
src/test/java/com/gooddata/notification/NotificationServiceTest.java
src/test/java/com/gooddata/notification/SubscriptionTest.java
src/test/java/com/gooddata/notification/TimerEventTest.java
src/test/resources/notification/channel.json
src/test/resources/notification/channelToCreate.json
src/test/resources/notification/condition.json
src/test/resources/notification/emailConfiguration.json
src/test/resources/notification/meta.json
src/test/resources/notification/metaToCreate.json
src/test/resources/notification/subscription.json
src/test/resources/notification/subscriptionToCreate.json
src/test/resources/notification/template.json
src/test/resources/notification/timerEvent.json

add support for notification channels and subscriptions

---

src/main/java/com/gooddata/account/AccountService.java
src/main/java/com/gooddata/auditevent/AuditEventService.java
src/main/java/com/gooddata/connector/ConnectorService.java
src/main/java/com/gooddata/dataload/OutputStageService.java
src/main/java/com/gooddata/dataload/processes/ProcessService.java
src/main/java/com/gooddata/dataset/DatasetService.java
src/main/java/com/gooddata/export/ExportService.java
src/main/java/com/gooddata/featureflag/FeatureFlagService.java
src/main/java/com/gooddata/gdc/GdcService.java
src/main/java/com/gooddata/md/MetadataService.java
src/main/java/com/gooddata/md/maintenance/ExportImportService.java
src/main/java/com/gooddata/model/ModelService.java
src/main/java/com/gooddata/notification/NotificationService.java
src/main/java/com/gooddata/project/ProjectService.java
src/main/java/com/gooddata/projecttemplate/ProjectTemplateService.java
src/main/java/com/gooddata/report/ReportService.java
src/main/java/com/gooddata/warehouse/WarehouseService.java

without these constructors gooddata-java is not backward compatible

Return constructors without GoodDataSettings to services

---

src/main/java/com/gooddata/executeafm/result/Data.java
src/main/java/com/gooddata/executeafm/result/DataList.java
src/main/java/com/gooddata/executeafm/result/DataValue.java
src/main/java/com/gooddata/executeafm/result/ExecutionResult.java
src/test/groovy/com/gooddata/executeafm/result/DataListTest.groovy
src/test/groovy/com/gooddata/executeafm/result/DataTest.groovy
src/test/groovy/com/gooddata/executeafm/result/DataValueTest.groovy
src/test/groovy/com/gooddata/executeafm/result/ExecutionResultTest.groovy

Resolves #555 by introducing the interface Data and its three kinds
- DataList, DataValue and NULL.

use dataList as execution result data

---

src/main/java/com/gooddata/executeafm/result/ExecutionResult.java
src/main/java/com/gooddata/executeafm/result/Warning.java
src/test/groovy/com/gooddata/executeafm/result/ExecutionResultTest.groovy
src/test/groovy/com/gooddata/executeafm/result/WarningTest.groovy
src/test/resources/executeafm/result/executionResultFull.json
src/test/resources/executeafm/result/warning.json

Introduce support for ExecutionResult's warnings

---

src/main/java/com/gooddata/executeafm/resultspec/AttributeSortAggregation.java
src/main/java/com/gooddata/executeafm/resultspec/AttributeSortItem.java
src/test/groovy/com/gooddata/executeafm/resultspec/AttributeSortItemTest.groovy
src/test/resources/executeafm/resultspec/attributeSortItemWithAggregation.json

Add 'aggregation' to AttributeSortItem

---

pom.xml
src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/executeafm/ExecuteAfmService.java
src/main/java/com/gooddata/executeafm/ExecutionResultException.java
src/main/java/com/gooddata/executeafm/ResultPage.java
src/main/java/com/gooddata/executeafm/response/ExecutionResponse.java
src/test/groovy/com/gooddata/GoodDataITBase.groovy
src/test/groovy/com/gooddata/executeafm/ExecuteAfmServiceIT.groovy
src/test/groovy/com/gooddata/executeafm/ExecutionResultExceptionTest.groovy
src/test/groovy/com/gooddata/executeafm/ResultPageTest.groovy
src/test/java/com/gooddata/executeafm/ExecuteAfmServiceAT.java

introduce ExecuteAfmService

---

src/test/java/com/gooddata/dataset/DatasetServiceAT.java

fix: match the changed error message in dataset upload

---

src/main/java/com/gooddata/executeafm/afm/AbsoluteDateFilter.java
src/main/java/com/gooddata/executeafm/afm/DateFilter.java
src/main/java/com/gooddata/executeafm/afm/NegativeAttributeFilter.java
src/main/java/com/gooddata/executeafm/afm/RelativeDateFilter.java
src/main/java/com/gooddata/md/visualization/VisualizationAttribute.java
src/main/java/com/gooddata/md/visualization/VisualizationConverter.java
src/main/java/com/gooddata/md/visualization/VisualizationObject.java
src/test/groovy/com/gooddata/md/visualization/BucketTest.groovy
src/test/groovy/com/gooddata/md/visualization/VisualizationObjectConverterTest.groovy
src/test/groovy/com/gooddata/md/visualization/VisualizationObjectTest.groovy
src/test/resources/md/visualization/complexVisualizationObject.json
src/test/resources/md/visualization/lineChart.json
src/test/resources/md/visualization/multipleAttributeBucketsVisualization.json

Resolves https://github.com/gooddata/gooddata-java/issues/583

Add converter from VisualizationObject to Execution

---

src/main/java/com/gooddata/md/visualization/VisualizationConverter.java
src/test/groovy/com/gooddata/md/visualization/VisualizationObjectConverterTest.groovy
src/test/groovy/com/gooddata/md/visualization/VisualizationObjectTest.groovy
src/test/resources/md/visualization/complexVisualizationObject.json
src/test/resources/md/visualization/multipleMeasureBucketsVisualization.json

resolves https://github.com/gooddata/gooddata-java/issues/584

Make measure filters in visualisation object voluntary for conversion

---

src/main/java/com/gooddata/md/visualization/VisualizationConverter.java
src/test/groovy/com/gooddata/md/visualization/VisualizationObjectConverterTest.groovy

Remove default sorting from ResultSpec in VisualizationConverter

---

src/main/java/com/gooddata/GoodData.java
src/main/java/com/gooddata/lcm/LcmEntities.java
src/main/java/com/gooddata/lcm/LcmEntity.java
src/main/java/com/gooddata/lcm/LcmEntityFilter.java
src/main/java/com/gooddata/lcm/LcmService.java
src/test/groovy/com/gooddata/lcm/LcmEntitiesTest.groovy
src/test/groovy/com/gooddata/lcm/LcmEntityFilterTest.groovy
src/test/groovy/com/gooddata/lcm/LcmEntityTest.groovy
src/test/groovy/com/gooddata/lcm/LcmServiceIT.groovy
src/test/resources/lcm/lcmEntities.json
src/test/resources/lcm/lcmEntitiesEmpty.json
src/test/resources/lcm/lcmEntity.json
src/test/resources/lcm/lcmEntityFull.json

introduce LcmService

---

src/main/java/com/gooddata/executeafm/afm/PopMeasureDefinition.java
src/main/java/com/gooddata/md/visualization/VOPopMeasureDefinition.java
src/test/groovy/com/gooddata/executeafm/afm/PopMeasureDefinitionTest.groovy
src/test/resources/executeafm/afm/popMeasureDefinitionWithOffset.json

Introduce support for offset in PoP measure

---

src/main/java/com/gooddata/md/MetadataService.java
src/test/java/com/gooddata/md/MetadataServiceTest.java

support irregular query type plurals in find by query resource

---

src/test/java/com/gooddata/executeafm/ExecuteAfmServiceAT.java

add acceptance test for ExecuteAfm#executeVisualization

---

pom.xml

This should get rid of unauthenticated remote code execution vulnerability
Fixes #609

raise jackson version

---

README.md
pom.xml

Upgrade to httpclient 4.5.5

---

pom.xml

See changelog: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8

Use patched jackson-databind dependency

---

src/main/java/com/gooddata/executeafm/afm/DerivedMeasureDefinition.java
src/main/java/com/gooddata/executeafm/afm/OverPeriodMeasureDefinition.java
src/main/java/com/gooddata/executeafm/afm/PopMeasureDefinition.java
src/main/java/com/gooddata/executeafm/afm/PreviousPeriodMeasureDefinition.java

Create a new interface for derived measures that will allow us to work with them in a unified way. The pull request resolves issue https://github.com/gooddata/gooddata-java/issues/622.

Introduce interface for derived measures

---

src/main/java/com/gooddata/executeafm/resultspec/LocatorItem.java
src/main/java/com/gooddata/executeafm/resultspec/TotalLocatorItem.java
src/test/groovy/com/gooddata/executeafm/resultspec/TotalLocatorItemTest.groovy
src/test/resources/executeafm/resultspec/totalLocatorItem.json

introduce totals measure sort locator in the execute AFM

---

src/main/java/com/gooddata/executeafm/afm/ArithmeticMeasureDefinition.java
src/main/java/com/gooddata/executeafm/afm/MeasureDefinition.java
src/test/groovy/com/gooddata/executeafm/afm/ArithmeticMeasureDefinitionTest.groovy
src/test/resources/executeafm/afm/arithmeticMeasureDefinition.json

Add support for new arithmetic measure definition

---

src/main/java/com/gooddata/executeafm/afm/ArithmeticMeasureDefinition.java
src/test/groovy/com/gooddata/executeafm/afm/ArithmeticMeasureDefinitionTest.groovy
src/test/resources/executeafm/afm/arithmeticMeasureDefinition.json

rename measures to measureIdentifiers in ArithmeticMeasureDefinition

---

src/main/java/com/gooddata/md/AbstractObj.java
src/main/java/com/gooddata/md/Meta.java
src/main/java/com/gooddata/md/ScheduledMail.java
src/main/java/com/gooddata/project/Project.java
src/test/java/com/gooddata/md/MetaTest.java
src/test/java/com/gooddata/md/ObjTest.java
src/test/resources/md/meta-withFlags.json

Added missing MD obj flags (AbstractObj.Meta.flags) property

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/lcm/LcmEntityFilter.java
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/lcm/LcmEntityFilterTest.groovy
gooddata-java/src/main/java/com/gooddata/sdk/service/lcm/LcmService.java
gooddata-java/src/test/groovy/com/gooddata/sdk/service/lcm/LcmServiceIT.groovy

Move LcmEntityFilter to model

---

src/main/java/com/gooddata/project/ProjectService.java
src/test/java/com/gooddata/project/ProjectServiceAT.java
src/test/java/com/gooddata/project/ProjectServiceIT.java
src/test/java/com/gooddata/project/ProjectServiceTest.java

We added check for URI in roles from `userRoles` param to `ProjectService.addUserToProject`.
We edited method `ProjectService.getRoleByUri` to set URI to the returned role.
This solves the issue https://github.com/gooddata/gooddata-java/issues/766.

Enhance ProjectService's adding of a user to project

---

gooddata-java/src/main/java/com/gooddata/sdk/service/retry/RetryableRestTemplate.java

Also removes fogotten debug output to stdout.

Log retried API calls

---

gooddata-java/src/main/java/com/gooddata/sdk/service/executeafm/ExecuteAfmService.java

make static properties of ExecuteAfmService public

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/account/SeparatorSettings.java
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/account/SeparatorSettingsTest.groovy
gooddata-java-model/src/test/resources/account/separators.json
gooddata-java/src/main/java/com/gooddata/sdk/service/account/AccountService.java
gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceAT.java
gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceIT.java
gooddata-java/src/test/resources/account/separators.json

add support for profile separator settings

---

pom.xml
src/test/resources/log4j.properties
src/test/resources/simplelogger.properties

Migrate to slf4j-simple logger in tests

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/gdc/RootLinks.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/gdc/RootLinksTest.java
gooddata-java-model/src/test/resources/gdc/gdc.json
gooddata-java/src/test/resources/gdc/gdc.json

fixes https://github.com/gooddata/gooddata-java/issues/851

Remove of usage of /releaseInfo resource

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/Restriction.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/md/RestrictionTest.java

Also add missing not-null checks to parameters
Fixes #856

Add equals to Restriction

---

gooddata-java/src/main/java/com/gooddata/sdk/service/auditevent/AuditEventPageRequest.java
gooddata-java/src/test/java/com/gooddata/sdk/service/auditevent/AuditEventPageRequestTest.java
pom.xml

depends on: https://github.com/gooddata/gooddata-rest-common/pull/58

Fix ZonedDateTime query params formatting

---

src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java

lower the limit query param number to allowed maximum in WarehouseServiceAT#listWarehouses

---

README.md
findBugsFilter.xml
gooddata-java/src/main/java/com/gooddata/sdk/service/AbstractService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/account/AccountService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/connector/ConnectorService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/dataload/processes/ProcessService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/dataset/DatasetService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/export/ExportService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/md/MetadataService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/md/maintenance/ExportImportService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/project/ProjectService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/project/model/ModelService.java
gooddata-java/src/main/java/com/gooddata/sdk/service/projecttemplate/ProjectTemplateService.java
pom.xml

Migrate to spring 5

---

gooddata-java/src/test/java/com/gooddata/sdk/service/project/ProjectServiceAT.java

Fix the wrongly refactored user listing cycle

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/projecttemplate/Template.java
gooddata-java-model/src/main/java/com/gooddata/sdk/model/projecttemplate/Templates.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/projecttemplate/TemplateTest.java
gooddata-java/src/main/java/com/gooddata/sdk/service/GoodData.java
gooddata-java/src/main/java/com/gooddata/sdk/service/GoodDataServices.java
gooddata-java/src/main/java/com/gooddata/sdk/service/projecttemplate/ProjectTemplateService.java
gooddata-java/src/test/java/com/gooddata/sdk/service/projecttemplate/ProjectTemplateServiceIT.java

Deprecate Project Templates (EOL 2019)

---

gooddata-java/src/test/java/com/gooddata/sdk/service/dataload/processes/ProcessServiceAT.java

Stabilize test ProcessServiceAT:
- On RAT instances CPU is quite busy which sometimes causes gcf task creation timeout.
- Workaround by retrying GIT deployment process 3 times, only fail tests after 3 attempts.

Stabilize test ProcessServiceAT

---

gooddata-java/src/main/java/com/gooddata/sdk/service/connector/ConnectorService.java
gooddata-java/src/test/java/com/gooddata/sdk/service/connector/ConnectorServiceIT.java

Fixes https://github.com/gooddata/gooddata-java/issues/945.

Add possibility to delete connectors integration

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/filter/ExtendedFilter.java
gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/filter/RankingFilter.java
gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/filter/RankingFilterOperator.java
gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/visualization/VisualizationConverter.java
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/filter/CompatibilityFilterTest.groovy
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/filter/ExtendedFilterTest.groovy
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/filter/RankingFilterOperatorTest.groovy
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/filter/RankingFilterTest.groovy
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/visualization/VisualizationConverterTest.groovy
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/visualization/VisualizationObjectTest.groovy
gooddata-java-model/src/test/resources/executeafm/afm/rankingFilter.json
gooddata-java-model/src/test/resources/executeafm/afm/rankingFilterWithAttributes.json
gooddata-java-model/src/test/resources/md/visualization/complexVisualizationObject.json
gooddata-java/src/test/resources/md/visualization/complexVisualizationObject.json

Solves https://github.com/gooddata/gooddata-java/issues/949

Introduce ranking filter

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/response/AttributeHeader.java
gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/response/AttributeHeaderTest.groovy
gooddata-java-model/src/test/resources/executeafm/response/attributeHeaderExceptType.json

Add "type" property to AttributeHeader so that the type of a display form can be passed to an AFM execution response

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/maintenance/ExportProject.java
gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/maintenance/ExportProjectArtifact.java
gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/maintenance/ExportProjectToken.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/md/maintenance/ExportProjectArtifactTest.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/md/maintenance/ExportProjectTest.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/md/maintenance/ExportProjectTokenTest.java
gooddata-java-model/src/test/resources/md/maintenance/exportArtifact.json
gooddata-java-model/src/test/resources/md/maintenance/exportProject-defaultVals.json
gooddata-java-model/src/test/resources/md/maintenance/exportProject.json
gooddata-java-model/src/test/resources/md/maintenance/importProject.json
gooddata-java/src/main/java/com/gooddata/sdk/service/md/maintenance/ExportImportService.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/maintenance/ExportImportServiceAT.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/maintenance/ExportImportServiceIT.java
gooddata-java/src/test/java/com/gooddata/sdk/service/util/ResponseErrorHandlerTest.java
gooddata-java/src/test/resources/dataset/taskStateError.json
gooddata-java/src/test/resources/gdc/gdcError.json
gooddata-java/src/test/resources/md/maintenance/exportProject-defaultVals.json
gooddata-java/src/test/resources/md/maintenance/exportProjectArtifact.json
gooddata-java/src/test/resources/md/maintenance/importProject.json

Add export/import of the whole project

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/account/Account.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/account/AccountTest.java
gooddata-java-model/src/test/resources/account/account-input.json
gooddata-java-model/src/test/resources/account/account.json
gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceAT.java
gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceIT.java
gooddata-java/src/test/resources/account/update-account.json

Fixes https://github.com/gooddata/gooddata-java/issues/1056

Add authenticationModes to Account.java

---

gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/Service.java
gooddata-java-model/src/test/java/com/gooddata/sdk/model/md/ServiceTest.java
gooddata-java-model/src/test/resources/md/service-timezone.json
gooddata-java/src/main/java/com/gooddata/sdk/service/md/MetadataService.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/MetadataServiceAT.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/MetadataServiceIT.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/MetadataServiceTest.java
gooddata-java/src/test/resources/md/service-timezone.json

Add workspace timezone setting

---

gooddata-java/src/test/java/com/gooddata/sdk/service/AbstractServiceTest.java
gooddata-java/src/test/java/com/gooddata/sdk/service/dataload/processes/ProcessServiceTest.java
gooddata-java/src/test/java/com/gooddata/sdk/service/dataset/DatasetServiceTest.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/MetadataServiceTest.java
gooddata-java/src/test/java/com/gooddata/sdk/service/md/maintenance/ExportImportServiceTest.java

To prepare for migration to Mockito v4.

Replace Mockito deprecated APIs

---

gooddata-java-model/src/test/resources/project/project-vertica.json
gooddata-java-model/src/test/resources/project/project.json
gooddata-java-model/src/test/resources/project/projects.json
gooddata-java/src/test/resources/project/project-deleted.json
gooddata-java/src/test/resources/project/project-loading.json
gooddata-java/src/test/resources/project/project-vertica.json
gooddata-java/src/test/resources/project/project.json
gooddata-java/src/test/resources/project/projects-for-user.json

We still want to test we're able to deserialize it when it's still on API.

Return links that are still on API to tests

---

pom.xml

Bumps gooddata-rest-common from 2.0.0 to 2.0.1

Bumps gooddata-rest-common from 2.0.0 to 2.0.1

---

pom.xml

Not to break builds at the New Year

Hardcode year for copyright headers
