gooddata/gooddata-java

pom.xml, src/main/java/com/gooddata/GoodData.java
Jackson2 on classpath breaks de/serialization this time via AllEncompassingFormHttpMessageConverter which uses classpath detection and favours Jackson2 over Jackson1.
Closes: #121 Relates: #80
=> explicitly set RestTemplate's message converters

src/main/java/com/gooddata/GoodData.java
Previously the ResponseErrorHandler was constructed with the default set of message converters which doesn't work with Jackson2 on the classpath
Relate: #121
=> construct ResponseErrorHandler with custom message converters

src/main/java/com/gooddata/report/NoDataReportException.java, src/main/java/com/gooddata/report/ReportService.java, src/test/java/com/gooddata/report/ReportServiceIT.java
It can be usefull to distinguish between no data and other error during
report export.
=> throw different exceptions during report exporting

pom.xml
It is not good practice to rely on transitive deps as your project can
be easily broken by updating your deps. All used dependencies should
be declared.
maven-dependecy-plugin is now configured to break build if any used dep
is not declared. Unfortunately problematic deps are shown only as
warnings.
=> BUILD: Check that all used dependencies are also declared

src/main/java/com/gooddata/md/AbstractObj.java, src/main/java/com/gooddata/md/Obj.java, src/main/java/com/gooddata/md/ObjNotFoundException.java
AbstractObj is useful ancestor keeping most of metadata objects, including those which can't be considered
as first class citizens (they are nested into another object and it is not possible to manipulate them directly)
closes #188
=> metadata AbstractObj no longer implements Obj

pom.xml
The 0.9.2 version has fixed logout, but only for calls of execute method with host. 0.9.3 correctly detects also the situation when full uri is given in http method.
closes #244
=> fix: use fixed version of gooddata-http-client with correct logout request recongnition

src/main/java/com/gooddata/GoodData.java, src/main/java/com/gooddata/UriPrefixer.java, src/main/java/com/gooddata/dataset/DatasetService.java, src/main/java/com/gooddata/gdc/DataStoreService.java, src/test/java/com/gooddata/AbstractGoodDataAT.java, src/test/java/com/gooddata/AbstractGoodDataIT.java, src/test/java/com/gooddata/JsonMatchers.java, src/test/java/com/gooddata/collections/UriPageTest.java, src/test/java/com/gooddata/dataload/processes/ScheduleTest.java, src/test/java/com/gooddata/dataset/DatasetServiceIT.java, src/test/java/com/gooddata/dataset/FailStatusTest.java, src/test/java/com/gooddata/gdc/DatastoreServiceAT.java
The root cause of the problem was in the 'sardine' library not following
HTTP 301 redirects when doing DELETE on resource on WebDav.
In case of GD WebDav infrastructure, when you want to delete collection,
you need to execute DELETE on resource with trailing '/', otherwise you
get HTTP 301 with correct location.
=> DataStoreService is now able to delete WebDav collections.

src/main/java/com/gooddata/md/MaqlAst.java, src/test/java/com/gooddata/JsonMatchers.java, src/test/java/com/gooddata/md/MetricTest.java
Fix the problem when Metric is created and later updated by MetadataService.
In case that Metric is created the Metric.MaqlAst.content might be null in some cases
which leads to failed call (400 MD server response) during update.
=> Metric.MaqlAst.content is serialized as 'absent' instead of null

src/main/java/com/gooddata/md/MetadataService.java
It's necessary to make those methods final and
that's not backward compatible.
Fixes #296
=> Add @SafeVarargs to MetadataService.usedBy methods

src/main/java/com/gooddata/md/MetadataService.java
Reverts martiner/gooddata-java#298 because it's not backward compatible. It will be postponed to v2.0.0
=> Revert "Add @SafeVarargs to MetadataService.usedBy methods"

src/main/java/com/gooddata/gdc/UriResponse.java, src/main/java/com/gooddata/md/DataLoadingColumn.java, src/main/java/com/gooddata/md/maintenance/ExportImportService.java, src/main/java/com/gooddata/md/maintenance/PartialMdArtifact.java, src/test/java/com/gooddata/md/DataLoadingColumnTest.java, src/test/java/com/gooddata/md/maintenance/PartialMdArtifactTest.java
Unfortunately the change in DataLoadingColumn is
not backward compatible. On the other hand this
Object has been added recently.
Fixes #301 (Replaces #300 PR)
=> Get rid of UriResponse from object APIs

src/main/java/com/gooddata/GoodData.java
Currently we use only RequestConfig, which is applied
after the connection is establish. However in certain
situations (i.e. when connected throughout proxy)
connecting include making requests, in such situations
defaultSocketConfig on ConnectionManager is used.
Fixes #335
=> Set DefaultSocketConfig with socket timeout

src/main/java/com/gooddata/md/Metric.java, src/test/java/com/gooddata/md/MetricTest.java, src/test/resources/md/metric-links.json
This field is added in R119, and because of Metric object doesn't ignore unknown fileds, the deserialization fails.
Close: #339
=> fix: ignore links field on metrics

src/main/java/com/gooddata/account/AccountService.java, src/test/java/com/gooddata/account/AccountServiceAT.java, src/test/java/com/gooddata/account/AccountServiceIT.java
This change is for the sake of consistency with project, data warehouse,... and it is not breaking backward compatibility, because it is introduced in unreleased version
=> rename getAccount() to getAccountById() and introduce getAccountByUri()

src/main/java/com/gooddata/md/report/AttributeInGrid.java
Also deprecate the constructor without alias, since empty String is not very useful value for alias.
fixes #359
=> fix: AttributeInGrid has always alias set

src/main/java/com/gooddata/dataload/processes/Schedule.java, src/test/java/com/gooddata/dataload/processes/ProcessServiceAT.java, src/test/java/com/gooddata/dataload/processes/ScheduleTest.java, src/test/resources/dataload/processes/schedule-input-all-fields.json, src/test/resources/dataload/processes/schedule-triggered-input.json, src/test/resources/dataload/processes/schedule-triggered.json, src/test/resources/dataload/processes/schedule.json
Issue #374 
- When creating schedule, you can either specify cron expression or different schedule, which triggers execution of created schedule (you cannot specify both)
-  You can also optionally set schedule name (which differs from default name of schedule set to name of executable)
=> Add creating schedules triggered by schedule and names for schedules

src/main/java/com/gooddata/dataload/processes/ProcessService.java, src/test/java/com/gooddata/dataload/processes/ProcessServiceAT.java, src/test/java/com/gooddata/dataload/processes/ProcessServiceIT.java, src/test/java/com/gooddata/dataload/processes/ProcessServiceTest.java
It makes no sense to require the project argument for update methods, as the object to update already contains the URI.
Similary we don't require project argument for remove methods.
=> introduce update methods without project argument

src/test/java/com/gooddata/dataload/processes/ProcessServiceAT.java
process was removed before schedule, this caused exception, when trying to remove schedule of removed process
=> Fixed order of tests in ProcessServiceAT

src/main/java/com/gooddata/md/report/Report.java, src/test/java/com/gooddata/md/report/ReportTest.java, src/test/resources/md/report/report-input.json
Also removing protected report's constructor since I believe it makes no sense to test
serialization of something what can't be created by SDK user.
resolves #384
=> fix invalid report's domain serialization

src/main/java/com/gooddata/Authentication.java, src/main/java/com/gooddata/GoodData.java, src/main/java/com/gooddata/GoodDataEndpoint.java, src/main/java/com/gooddata/authentication/LoginPasswordAuthentication.java, src/main/java/com/gooddata/authentication/SstAuthentication.java, src/test/java/com/gooddata/AbstractGoodDataAT.java, src/test/java/com/gooddata/AbstractGoodDataIT.java, src/test/java/com/gooddata/GoodDataEndpointTest.java, src/test/java/com/gooddata/authentication/LoginPasswordAuthenticationTest.java, src/test/java/com/gooddata/authentication/SstAuthenticationTest.java
=> create http client factory and encapsulate GoodData hostname, port and protocol

src/main/java/com/gooddata/GoodDataRestException.java, src/main/java/com/gooddata/gdc/ErrorStructure.java, src/main/java/com/gooddata/gdc/ErrorStructureDeserializer.java, src/main/java/com/gooddata/gdc/GdcError.java, src/main/java/com/gooddata/util/ResponseErrorHandler.java, src/test/java/com/gooddata/util/ResponseErrorHandlerTest.java
Resolves #395.
Custom deserializer for ErrorStructure and descendant GdcError created. Unfortunately it's not possible to
deserialize exactly the ErrorStructure instance - the on purpose descendant is returned instead.
=> fix: enable ResponseErrorHandler to read both known gdc error json structures

src/main/java/com/gooddata/collections/MultiPageList.java, src/main/java/com/gooddata/collections/PageRequest.java, src/main/java/com/gooddata/collections/PageableList.java, src/main/java/com/gooddata/collections/PageableListSerializer.java, src/main/java/com/gooddata/collections/UriPage.java, src/main/java/com/gooddata/dataload/processes/ProcessService.java, src/main/java/com/gooddata/project/ProjectService.java, src/main/java/com/gooddata/warehouse/WarehouseService.java, src/test/java/com/gooddata/collections/MultiPageListTest.java, src/test/java/com/gooddata/collections/PageRequestTest.java, src/test/java/com/gooddata/collections/PageableListTest.java, src/test/java/com/gooddata/collections/UriPageTest.java, src/test/java/com/gooddata/dataload/processes/ProcessServiceAT.java, src/test/java/com/gooddata/warehouse/WarehouseServiceIT.java, src/test/resources/warehouse/users-with-next-page-link.json
PageableList should be able to easily iterate over all results on multiple pages rather than making the user of PageableList worry about implementing such iteration.
=> iterate/stream over multiple pages with MultiPageList, closes #479

src/main/java/com/gooddata/collections/PageableList.java, src/test/java/com/gooddata/collections/PageableListTest.java
this fixes NPE in `hashCode()` and `equals()` due to nullable fields
=> fix broken hashCode/equals in PageableList

src/main/java/com/gooddata/warehouse/WarehouseS3Credentials.java, src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsList.java, src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsListDeserializer.java, src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsListSerializer.java, src/main/java/com/gooddata/warehouse/WarehouseS3CredentialsNotFoundException.java, src/main/java/com/gooddata/warehouse/WarehouseService.java, src/main/java/com/gooddata/warehouse/WarehouseTask.java, src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsListTest.java, src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsTest.java, src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java, src/test/java/com/gooddata/warehouse/WarehouseServiceIT.java, src/test/java/com/gooddata/warehouse/WarehouseTaskTest.java, src/test/resources/warehouse/s3Credentials-create.json, src/test/resources/warehouse/s3Credentials-full.json, src/test/resources/warehouse/s3Credentials-get.json, src/test/resources/warehouse/s3CredentialsList.json, src/test/resources/warehouse/warehouseTask-finished.json
In order to use COPY FROM S3 functionality, users need to store their S3 credentials in Vertica. This adds support for POST and GET resource to allow the users to add/list credentials.
=> add and list warehouse S3 credentials

src/test/java/com/gooddata/featureflag/FeatureFlagServiceAT.java
The API is eventually consistent and it sometime takes some time the flag is really removed. In the SDK we don't have to test correctness of the API
=> just validate the delete call doesn't end with error

src/main/java/com/gooddata/AbstractPollHandler.java, src/main/java/com/gooddata/AbstractService.java, src/main/java/com/gooddata/PollHandler.java, src/test/java/com/gooddata/AbstractServiceTest.java, src/test/java/com/gooddata/PollHandlerIT.java, src/test/java/com/gooddata/dataload/processes/ProcessServiceTest.java
=> Use URI because it is not double-encoded by RestTemplate

src/main/java/com/gooddata/warehouse/WarehouseS3Credentials.java, src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsExceptionTest.java, src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsListTest.java, src/test/java/com/gooddata/warehouse/WarehouseS3CredentialsTest.java, src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java, src/test/java/com/gooddata/warehouse/WarehouseServiceIT.java, src/test/resources/warehouse/s3Credentials-full.json, src/test/resources/warehouse/s3Credentials-get.json, src/test/resources/warehouse/s3CredentialsList.json
#This PR gets rid of `updatedBy` field from S3 DTO and its JSON, and leaves only `links.updatedBy` (the URI to updater's profile). Closes #495 
`updatedBy` field of `WarehouseS3Credentials` was for internal use only and should not be accessed by the users of the SDK. Therefore it is now being removed. The users of SDK should use `getUpdatedByUri()` instead.
`withLinks` methods are also being removed, as well as public constructor which was marked as not intended for end users
=> remove updatedBy field in S3 DTO

pom.xml, src/main/java/com/gooddata/auditevent/AuditEventPageRequest.java, src/test/java/com/gooddata/auditevent/AuditEventPageRequestTest.java
Without equals and hashcode overridden really unexpected things happen when comparing or mocking such classes
=> add equals and hashcode because parent class has them

src/main/java/com/gooddata/md/BulkGet.java, src/main/java/com/gooddata/md/BulkGetUris.java, src/main/java/com/gooddata/md/MetadataService.java, src/main/java/com/gooddata/md/Obj.java, src/test/java/com/gooddata/md/MetadataServiceAT.java, src/test/java/com/gooddata/md/MetadataServiceIT.java, src/test/java/com/gooddata/md/MetadataServiceTest.java, src/test/resources/md/bulk-get.json
Metadata API supports bulk retrieval of objects by their URIs. The SDK
did not support this, so one had to retrieve objects one by one. Now,
with the getObjsByUris() methods it is possible to retrieve multiple
objects using a single request.
=> Add support for metadata bulk get

src/main/java/com/gooddata/md/ScheduledMailWhen.java
Old links is no longer valid as old version of the library was probably removed from the CPAN.
=> Fix link to Date::Manip::Recur documentation

src/main/java/com/gooddata/executeafm/response/ResultDimension.java, src/main/java/com/gooddata/executeafm/resultspec/Dimension.java, src/test/groovy/com/gooddata/executeafm/ExecutionTest.groovy, src/test/groovy/com/gooddata/executeafm/response/ExecutionResponseTest.groovy, src/test/groovy/com/gooddata/executeafm/response/ResultDimensionTest.groovy, src/test/groovy/com/gooddata/executeafm/resultspec/DimensionTest.groovy, src/test/groovy/com/gooddata/executeafm/resultspec/ResultSpecTest.groovy, src/test/resources/executeafm/executionFull.json, src/test/resources/executeafm/response/executionResponse.json, src/test/resources/executeafm/response/resultDimension.json, src/test/resources/executeafm/resultspec/dimension.json, src/test/resources/executeafm/resultspec/dimensionFull.json, src/test/resources/executeafm/resultspec/resultSpec.json
This is backward incompatible, however, there is no service yet using it.
Resolves #545
=> fix: remove redundant name in executeafm dtos

src/main/java/com/gooddata/executeafm/response/AttributeHeader.java, src/main/java/com/gooddata/executeafm/response/AttributeInHeader.java, src/test/groovy/com/gooddata/executeafm/response/AttributeHeaderTest.groovy, src/test/groovy/com/gooddata/executeafm/response/AttributeInHeaderTest.groovy, src/test/groovy/com/gooddata/executeafm/response/ExecutionResponseTest.groovy, src/test/groovy/com/gooddata/executeafm/response/ResultDimensionTest.groovy, src/test/resources/executeafm/response/attributeHeader.json, src/test/resources/executeafm/response/attributeHeaderFull.json, src/test/resources/executeafm/response/attributeInHeader.json, src/test/resources/executeafm/response/executionResponse.json, src/test/resources/executeafm/response/resultDimension.json
The ExecutionResponse should inform client about which attribute does the header belongs to (not only display form)
Resolves #559
=> Introduce AttributeHeader.formOf

release.sh
On Mac, we need to provide extension for backup-file - but when empty string is provided, it behaves exactly the same as `-i` (without argument) on Linux
=> Make `release.sh` Mac compatible

src/main/java/com/gooddata/executeafm/afm/MeasureDefinition.java, src/main/java/com/gooddata/executeafm/afm/ObjIdentifierUtilities.java, src/main/java/com/gooddata/executeafm/afm/ObjQualifierConverter.java, src/main/java/com/gooddata/executeafm/afm/OverPeriodDateAttribute.java, src/main/java/com/gooddata/executeafm/afm/OverPeriodMeasureDefinition.java, src/main/java/com/gooddata/executeafm/afm/PopMeasureDefinition.java, src/main/java/com/gooddata/executeafm/afm/PreviousPeriodDateDataSet.java, src/main/java/com/gooddata/executeafm/afm/PreviousPeriodMeasureDefinition.java, src/main/java/com/gooddata/executeafm/afm/SimpleMeasureDefinition.java, src/main/java/com/gooddata/md/visualization/VOPopMeasureDefinition.java, src/test/groovy/com/gooddata/executeafm/afm/MeasureDefinitionTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/ObjIdentifierUtilitiesTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/OverPeriodDateAttributeTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/OverPeriodMeasureDefinitionTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/PopMeasureDefinitionTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/PreviousPeriodDateDataSetTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/PreviousPeriodMeasureDefinitionTest.groovy, src/test/groovy/com/gooddata/executeafm/afm/SimpleMeasureDefinitionTest.groovy, src/test/resources/executeafm/afm/overPeriodDateAttribute.json, src/test/resources/executeafm/afm/overPeriodMeasureDefinition.json, src/test/resources/executeafm/afm/overPeriodMeasureDefinitionWithTwoAttributes.json, src/test/resources/executeafm/afm/popMeasureDefinitionWithOffset.json, src/test/resources/executeafm/afm/previousPeriodDateDataSet.json, src/test/resources/executeafm/afm/previousPeriodMeasureDefinition.json, src/test/resources/executeafm/afm/previousPeriodMeasureDefinitionWithTwoDataSets.json
The pull request contains two commits:
One for the issue https://github.com/gooddata/gooddata-java/issues/611 that reverts changes introduced via https://github.com/gooddata/gooddata-java/issues/597 and second that supports new PoP implementation reported via https://github.com/gooddata/gooddata-java/issues/612.
The pull request contains changes to the way how measure definitions are copied when they contain identifier object qualifiers. Previously, all the definitions contained 1 object qualifier at maximum. The new definitions can have more of them in its child objects, therefore, the interface of the `MeasureDefinition` had to be changed to reflect this fact. I consulted the change with the late Jan Pradac.
API changes:
```
OverPeriodMeasureDefinition = {
overPeriodMeasure: { …
```
=> Introduce support for Over period and Previous period measure definition

src/main/java/com/gooddata/md/AttributeDisplayForm.java, src/test/java/com/gooddata/md/AttributeDisplayFormTest.java
Mainly same field name 'content' as in DisplayForm parent was causing chaos.
=> Differentiate AttributeContent from Content

src/main/java/com/gooddata/md/visualization/VisualizationConverter.java, src/main/java/com/gooddata/md/visualization/VisualizationObject.java, src/test/groovy/com/gooddata/md/visualization/VisualizationConverterTest.groovy
We wanted to convert objects of VisualizationObject and VisualizationClass that we obtained beforehand, but we were forced to write some boilerplate function that returned the VisualizationClass instead of providing the VisualizationClass directly. The modified methods simply allow to provide the VisualizationClass directly, while still keeping the backward compatibility with previous approach.
In addition, new check was implemented that checks whether the VisualizationClass URI matches with the URI that VisualizationObject contains. If you try to create convert incompatible objects, exception will be thrown.
Fixes #686
=> Simplified VisualizationConverter methods for Execution conversion

.travis.yml
Add `-B` (non-interactive/batch mode) to hide download progress indication.
Fixes #690
=> Shorten mvn console output in Travis

src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java, src/test/java/com/gooddata/connector/Zendesk4ProcessExecutionTest.java, src/test/resources/connector/process-execution-recoverable.json, src/test/resources/connector/process-execution-recoveryInProgress.json
We need to send information if a recovery is in progress ('recoveryInProgress' flag) and if the newly started process should use recoverable feature ('recoverable' flag).
This solves the issue https://github.com/gooddata/gooddata-java/issues/724.
=> Introduce recovery related fields in Zendesk4ProcessExecution

README.md, pom.xml, src/main/java/com/gooddata/GoodData.java, src/main/java/com/gooddata/GoodDataSettings.java, src/main/java/com/gooddata/retry/GetServerErrorRetryStrategy.java, src/main/java/com/gooddata/retry/RetrySettings.java, src/main/java/com/gooddata/retry/RetryStrategy.java, src/main/java/com/gooddata/retry/RetryableRestTemplate.java, src/test/groovy/com/gooddata/retry/RetrySettingsTest.groovy, src/test/groovy/com/gooddata/retry/RetryableRestTemplateTest.groovy, src/test/java/com/gooddata/connector/ConnectorServiceIT.java
Currently only for GET method and some kinds of HTTP 5XX status.
=> Add retry support when GD endpoint is unvailable

src/main/java/com/gooddata/GoodData.java
This prevents warnings like Invalid cookie header: ...Invalid 'expires' attribute: Tue, 2 Jul 2019 20:46:00 GMT
Resolves #815
=> Use standard cookie specs

.travis.yml
https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide/
https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
=> Use OpenJDK instead of Oracle on Travis

src/main/java/com/gooddata/notification/Subscription.java, src/test/java/com/gooddata/notification/SubscriptionTest.java, src/test/resources/notification/subscriptionWithSubject.json
Currently, it's impossible to specify the subscription email subject, only field for the email body template is defined. The subject added as per documentation.
Fixes https://github.com/gooddata/gooddata-java/issues/842
=> Add email subject to subscription

README.md
The badge URL created according [this issue comment](https://github.com/maxcellent/javadoc.io/issues/45#issuecomment-691733616).
=> README: show javadoc-model version in its badge

gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AccessLog.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AccessLogs.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AccessLogsDeserializer.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/auditevent/AccessLogsSerializer.java, gooddata-java-model/src/test/java/com/gooddata/sdk/model/auditevent/AccessLogTest.java, gooddata-java-model/src/test/java/com/gooddata/sdk/model/auditevent/AccessLogsTest.java, gooddata-java-model/src/test/resources/auditevents/accessLog.json, gooddata-java-model/src/test/resources/auditevents/accessLogs.json, gooddata-java-model/src/test/resources/auditevents/emptyAccessLogs.json, gooddata-java/src/main/java/com/gooddata/sdk/service/auditevent/AuditEventPageRequest.java, gooddata-java/src/main/java/com/gooddata/sdk/service/auditevent/TimeFilterPageRequest.java, gooddata-java/src/test/java/com/gooddata/sdk/service/auditevent/TimeFilterPageRequestTest.java
Fixes https://github.com/gooddata/gooddata-java/issues/1004
=> Add support for AccessLog API

gooddata-java/src/main/java/com/gooddata/sdk/service/RequestIdInterceptor.java, gooddata-java/src/main/java/com/gooddata/sdk/service/ResponseMissingRequestIdInterceptor.java, gooddata-java/src/main/java/com/gooddata/sdk/service/gdc/DataStoreService.java, gooddata-java/src/main/java/com/gooddata/sdk/service/gdc/GdcSardine.java, gooddata-java/src/main/java/com/gooddata/sdk/service/gdc/GdcSardineException.java, gooddata-java/src/main/java/com/gooddata/sdk/service/gdc/GdcSardineResponseHandler.java, gooddata-java/src/main/java/com/gooddata/sdk/service/httpcomponents/SingleEndpointGoodDataRestProvider.java, gooddata-java/src/test/java/com/gooddata/sdk/service/gdc/DatastoreServiceAT.java
Added 'RequestIdInterceptor' on the apache http client to generate 'requestId' for the client requests. It wasn't added to Spring 'RestTemplate' because the Sardine client doesn't use it.
Added 'ResponseMissingRequestIdInterceptor' on the apache http client to add missing 'X-GDC-REQUEST' header in responses coming from WebDav server.
Added the 'requestId' information to exceptions to easier tracking the problem.
=> #621 - add the logging of requestId

src/main/java/com/gooddata/GoodData.java, src/main/java/com/gooddata/RequestIdInterceptor.java, src/main/java/com/gooddata/ResponseMissingRequestIdInterceptor.java, src/main/java/com/gooddata/gdc/DataStoreService.java, src/main/java/com/gooddata/gdc/GdcSardine.java, src/main/java/com/gooddata/gdc/GdcSardineException.java, src/main/java/com/gooddata/gdc/GdcSardineResponseHandler.java, src/test/java/com/gooddata/gdc/DatastoreServiceAT.java
Added 'RequestIdInterceptor' on the apache http client to generate 'requestId' for the client requests. It wasn't added to Spring 'RestTemplate' because the Sardine client doesn't use it.
Added 'ResponseMissingRequestIdInterceptor' on the apache http client to add missing 'X-GDC-REQUEST' header in responses coming from WebDav server.
Added the 'requestId' information to exceptions to easier tracking the problem.
=> #621 - add the logging of requestId (port to 2.35.*)

gooddata-java-model/src/main/java/com/gooddata/sdk/model/account/Account.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/account/Accounts.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/account/AccountsDeserializer.java, gooddata-java-model/src/test/java/com/gooddata/sdk/model/account/AccountsTest.java, gooddata-java-model/src/test/resources/account/accounts.json, gooddata-java/src/main/java/com/gooddata/sdk/service/account/AccountNotFoundException.java, gooddata-java/src/main/java/com/gooddata/sdk/service/account/AccountService.java, gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceAT.java, gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceIT.java, gooddata-java/src/test/resources/account/account-by-email-empty-response.json, gooddata-java/src/test/resources/account/account-by-email.json
fixes 1064
Its work in progress, please comment what tests are missing, not sure how to handle response in case of array of items.
=> 1064 get user by login

gooddata-java-model/src/main/java/com/gooddata/sdk/model/project/Project.java, gooddata-java-model/src/test/java/com/gooddata/sdk/model/project/ProjectTest.java, gooddata-java-model/src/test/resources/project/project-vertica.json, gooddata-java-model/src/test/resources/project/project.json, gooddata-java-model/src/test/resources/project/projects.json, gooddata-java/src/test/resources/project/project-deleted.json, gooddata-java/src/test/resources/project/project-loading.json, gooddata-java/src/test/resources/project/project-vertica.json, gooddata-java/src/test/resources/project/project.json, gooddata-java/src/test/resources/project/projects-for-user.json
This service has been removed from platform long time ago and
those links are not on the API anymore.
=> Deprecate getEventStores links

gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/visualization/Bucket.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/visualization/VisualizationConverter.java, gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/visualization/VisualizationObject.java, gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/visualization/BucketTest.groovy, gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/visualization/VisualizationConverterTest.groovy, gooddata-java-model/src/test/resources/executeafm/afm/complextTableWithTotalsConvertedAfm.json, gooddata-java-model/src/test/resources/executeafm/executionComplexTableConverted.json, gooddata-java-model/src/test/resources/md/visualization/complexTableWithTotals.json, gooddata-java-model/src/test/resources/md/visualization/mixedBucketWithTotals.json
* Introduces `totals` field in the visualization `Bucket`
* Adds new AFM execution conversion methods with totals support:
* `VisualizationConverter.convertToResultSpecWithTotals`
* `VisualizationConverter.convertToAfmWithNativeTotals`
* `VisualizationConverter.convertToExecutionWithTotals`
* Keeps old conversion methods (without `totals` support) for the backward-compatibility.
=> Introduce totals support in visualizations and their conversions
